name: GUIManager
version: @version@
main: com.mcdragonmasters.guiManager.GUIManager
api-version: '1.21.8'
load: STARTUP
authors: [MCdragonmasters]
description: hi
dependencies:
  server:
    Vault:
      load: BEFORE
      required: true
      join-classpath: true